version: "3.9"

networks:
  cashmachine_network:
    driver: bridge
    name: cashmachine_network

services:
  cashmachine_redis:
    image: redis:7-alpine
    container_name: cashmachine_redis
    restart: unless-stopped
    networks:
      - cashmachine_network
    volumes:
      - cashmachine_redis_data:/data
    command: redis-server --maxmemory 256mb --maxmemory-policy allkeys-lru

  cashmachine_api:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: cashmachine_api
    restart: unless-stopped
    networks:
      - cashmachine_network
    env_file: .env
    depends_on:
      - cashmachine_redis
    ports:
      - "127.0.0.1:3011:3011"

  cashmachine_frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
      args:
        - NEXT_PUBLIC_API_URL=${NEXT_PUBLIC_API_URL}
        - NEXT_PUBLIC_WS_URL=${NEXT_PUBLIC_WS_URL}
        - NEXT_PUBLIC_APP_URL=${NEXT_PUBLIC_APP_URL}
    container_name: cashmachine_frontend
    restart: unless-stopped
    networks:
      - cashmachine_network
    env_file: .env
    depends_on:
      - cashmachine_api

  cashmachine_nginx:
    image: nginx:alpine
    container_name: cashmachine_nginx
    restart: unless-stopped
    networks:
      - cashmachine_network
    ports:
      - "0.0.0.0:8002:80"
    volumes:
      - ./nginx/cashmachine.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - cashmachine_frontend
      - cashmachine_api

volumes:
  cashmachine_redis_data:
